### ISSUE TITLE
Version 0.5.0 broke builds on Linux

### ISSUE THREAD

**Issue by DASPRiD** [alexrsagen/rs-nfc1-sys#5]
The following commit for version 0.5.0 introduced a regression on Linux: https://github.com/alexrsagen/rs-nfc1-sys/commit/eb3f2af6b21ee8c1027d4039d2e567a66631f210

When trying to build on Linux, the following error pops up: `use of undeclared crate or module find_winsdk`. This is because in the head of the file, the `extern crate` is excluded on non windows, but the code is still looking for it. For now I'm just rolling back to v0.4.1.

**Comment by alexrsagen** [comment]
Can reproduce.
<details><summary>Build error</summary>
<pre>
[...]
error[E0433]: failed to resolve: use of undeclared crate or module `find_winsdk`
  --> build.rs:63:30
   |
63 |             if let Ok(Some(winsdk)) = find_winsdk::SdkInfo::find(find_winsdk::SdkVersion::Any) {
   |                                       ^^^^^^^^^^^ use of undeclared crate or module `find_winsdk`

[...]</pre>
</details>

Pushing a fix now.
